/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package bkhosteldevs;

import java.awt.*;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.RandomAccessFile;
import java.nio.file.Paths;
import java.util.Date;
import javax.swing.*;

/**
 *
 * @author rodri
 */
public class FReserva extends javax.swing.JDialog {

    public static final String RESERVAS_FILE = Paths.get("src", "docs", "reservas.dat").toString();

    void crearReserva(Reservas reserva, String ruta) {
        if (reserva != null) {
            try {
                ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(ruta, true));
                oos.writeObject(reserva);
                oos.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }

    public void verReservas() {
        Reservas reserva;
        try {
            FileInputStream fis = new FileInputStream(RESERVAS_FILE);
            ObjectInputStream ois = new ObjectInputStream(fis);
            Object object = ois.readObject();
            if (object instanceof Reservas) {
                reserva = (Reservas) object;
                System.out.println(reserva.toString());
            }
        } catch (Exception e) {
        }
    }
    ButtonGroup jButtonGroup;

    public enum eTipoEvento {
        CONGRESO, BANQUETE, JORNADA
    }
    eTipoEvento eEvento;

    public enum eTipoCocina {
        Chef, NA, Buffet, Carta
    }
    eTipoCocina eCocina = eTipoCocina.Carta;
    public static final int RET_CANCEL = 0;
    public static final int RET_OK = 1;
    String nombre, telefono, tipoEvento, tipoCocina;
    Date fecha;
    Reservas reserva;
    int numDias, plazas;
    boolean boolHabitaciones;

    public void flagTipoEv(boolean flag) {
        jLabelJornadas.setEnabled(flag);
        jSpinnerJornadas.setEnabled(flag);
        jCheckBoxHabitaciones.setEnabled(flag);
    }
//
//    public void añadirTooltip(Component c) {
//        if (c.getClass().equals(JLabel.class)) {
//            ((JLabel)c).setToolTipText(c.getName());
//        }
//    }

    /**
     * Creates new form FReserva
     */
    public FReserva(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLayout(new FlowLayout());
        flagTipoEv(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelCocina = new javax.swing.JLabel();
        jCheckBoxHabitaciones = new javax.swing.JCheckBox();
        jButtonGroup = new ButtonGroup();
        jRButtonChef = new javax.swing.JRadioButton();
        jRButtonCarta = new javax.swing.JRadioButton();
        jRButtonBuffet = new javax.swing.JRadioButton();
        jRButtonNA = new javax.swing.JRadioButton();

        jButtonGroup.add(jRButtonBuffet);
        jButtonGroup.add(jRButtonCarta);
        jButtonGroup.add(jRButtonChef);
        jButtonGroup.add(jRButtonNA);

        jFormattedTextFieldTelefono = new javax.swing.JFormattedTextField();
        jLabelNombre = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        spinFecha = new javax.swing.JSpinner();
        jLabelFecha = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jLabelPlazas = new javax.swing.JLabel();
        jSpinnerPlazas = new javax.swing.JSpinner();
        jLabelJornadas = new javax.swing.JLabel();
        jSpinnerJornadas = new javax.swing.JSpinner();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelCocina.setText("Cocina");
        jLabelCocina.setToolTipText(this.getTitle());
        jLabelCocina.setName("jLabelCocina"); // NOI18N

        jCheckBoxHabitaciones.setText("Habitaciones");
        jCheckBoxHabitaciones.setToolTipText("Selecciona esta opción para reservar habitaciones para los invitados al evento\n");
        jCheckBoxHabitaciones.setName("jCheckBoxHabitaciones"); // NOI18N
        jCheckBoxHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxHabitacionesActionPerformed(evt);
            }
        });

        jRButtonChef.setText(eCocina.Chef.name());
        jRButtonChef.setToolTipText("Opción recomendación del chef");
        jRButtonChef.setName("jRButtonChef"); // NOI18N

        jRButtonCarta.setText(eCocina.Carta.name());
        jRButtonCarta.setToolTipText("Opción carta abierta");
        jRButtonCarta.setName("jRButtonCarta"); // NOI18N
        jRButtonCarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRButtonCartaActionPerformed(evt);
            }
        });

        jRButtonBuffet.setText(eCocina.Buffet.name());
        jRButtonBuffet.setToolTipText("Buffet libre");
        jRButtonBuffet.setName("jRButtonBuffet"); // NOI18N
        jRButtonBuffet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRButtonBuffetActionPerformed(evt);
            }
        });

        jRButtonNA.setText(eCocina.NA.name());
        jRButtonNA.setToolTipText("No aplica. Sin cocina");
        jRButtonNA.setName("jRButtonNA"); // NOI18N
        jRButtonNA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRButtonNAActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldTelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTelefono.setToolTipText("Introduce tu teléfono");
        jFormattedTextFieldTelefono.setMaximumSize(new java.awt.Dimension(9, 9));
        jFormattedTextFieldTelefono.setName("jFormattedTextFieldTelefono"); // NOI18N

        jLabelNombre.setText("Nombre");
        jLabelNombre.setToolTipText(this.getTitle());
        jLabelNombre.setMinimumSize(new java.awt.Dimension(40, 16));
        jLabelNombre.setName("jLabelNombre"); // NOI18N

        jLabelTelefono.setText("Teléfono");
        jLabelTelefono.setToolTipText(this.getTitle());
        jLabelTelefono.setName("jLabelTelefono"); // NOI18N

        jTextFieldNombre.setColumns(15);
        jTextFieldNombre.setToolTipText("Introduce tu nombre\n");
        jTextFieldNombre.setName("jTextFieldNombre"); // NOI18N

        spinFecha.setModel(new javax.swing.SpinnerDateModel());
        spinFecha.setToolTipText("Introduce la fecha de inicio del evento");
        spinFecha.setName("spinFecha"); // NOI18N

        jLabelFecha.setText("Fecha reserva");
        jLabelFecha.setToolTipText(this.getTitle());
        jLabelFecha.setName("jLabelFecha"); // NOI18N

        jLabelTipo.setText("Tipo de evento");
        jLabelTipo.setToolTipText(this.getTitle());
        jLabelTipo.setName("jLabelTipo"); // NOI18N

        jComboBoxTipo.setModel(new DefaultComboBoxModel(eTipoEvento.values()));
        jComboBoxTipo.setToolTipText("Elige el tipo de evento");
        jComboBoxTipo.setName("jComboBoxTipo"); // NOI18N
        jComboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoActionPerformed(evt);
            }
        });

        jLabelPlazas.setText("Plazas :");
        jLabelPlazas.setToolTipText(this.getTitle());
        jLabelPlazas.setName("jLabelPlazas"); // NOI18N

        jSpinnerPlazas.setToolTipText("Número de personas que asistirán al evento");
        jSpinnerPlazas.setName("jSpinnerPlazas"); // NOI18N

        jLabelJornadas.setText("Jornadas:");
        jLabelJornadas.setToolTipText(this.getTitle());
        jLabelJornadas.setName("jLabelJornadas"); // NOI18N

        jSpinnerJornadas.setToolTipText("Duración del evento (dias)");
        jSpinnerJornadas.setName("jSpinnerJornadas"); // NOI18N

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //Esta linea me genera un error : Exception in thread "AWT-EventQueue-0" java.lang.UnsupportedOperationException: Not supported yet.
                //  okButtonActionPerformed(evt);
                nombre = jTextFieldNombre.getText();
                telefono = jFormattedTextFieldTelefono.getText();
                // tipoEvento ya se guarda en el listener del jcombobox
                plazas = (Integer) jSpinnerPlazas.getValue();
                tipoCocina = jButtonGroup.getSelection().toString();
                fecha = (Date) spinFecha.getValue();
                System.out.println("fecha" + fecha.toString());

                reserva = new Reservas(nombre, telefono, tipoEvento, plazas, tipoCocina, fecha);
                if (jComboBoxTipo.getSelectedItem().equals(eEvento.CONGRESO)) {
                    numDias = (Integer) jSpinnerJornadas.getValue();
                    reserva.setNumDias(numDias);
                    if (jCheckBoxHabitaciones.isSelected()) {
                        reserva.setBoolHabitaciones(true);
                    } else {
                        reserva.setBoolHabitaciones(false);
                    }
                }
                System.err.println(reserva.toString());
                crearReserva(reserva, RESERVAS_FILE);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(spinFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jSpinnerJornadas, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jRButtonCarta))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jRButtonNA)
                                                        .addComponent(jCheckBoxHabitaciones))))
                                .addGap(26, 26, 26)
                                .addComponent(cancelButton)
                                .addContainerGap(75, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabelJornadas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabelPlazas)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jSpinnerPlazas, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabelCocina, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jRButtonChef)
                                                        .addGap(15, 15, 15)
                                                        .addComponent(jRButtonBuffet))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(1, 1, 1)
                                                        .addComponent(jLabelTipo)
                                                        .addGap(12, 12, 12)
                                                        .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(12, 12, 12)
                                                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(30, 30, 30)
                                                        .addComponent(jLabelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabelTelefono)
                                                        .addGap(12, 12, 12)
                                                        .addComponent(jFormattedTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addContainerGap(89, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(spinFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                                .addGap(70, 70, 70)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jSpinnerJornadas)
                                        .addComponent(jCheckBoxHabitaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(105, 105, 105)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jRButtonCarta, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                                        .addComponent(jRButtonNA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(71, 71, 71)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(okButton)
                                        .addComponent(cancelButton))
                                .addContainerGap())
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(3, 3, 3)
                                                        .addComponent(jLabelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                                                        .addGap(7, 7, 7)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                        .addGap(3, 3, 3)
                                                                        .addComponent(jLabelTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addGap(3, 3, 3))
                                                                .addComponent(jFormattedTextFieldTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGap(18, 18, 18)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jComboBoxTipo)
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                        .addGap(3, 3, 3)
                                                                        .addComponent(jLabelTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addGap(3, 3, 3)))
                                                        .addGap(17, 17, 17))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                        .addGap(8, 8, 8)
                                                                        .addComponent(jLabelFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                        .addGap(83, 83, 83)))
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabelJornadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(34, 34, 34)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(6, 6, 6)
                                                        .addComponent(jLabelPlazas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addComponent(jSpinnerPlazas))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(19, 19, 19)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jRButtonChef, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jRButtonBuffet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jLabelCocina)))
                                        .addContainerGap(131, Short.MAX_VALUE)))
        );

        getRootPane().setDefaultButton(okButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxHabitacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxHabitacionesActionPerformed

    private void jRButtonCartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRButtonCartaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRButtonCartaActionPerformed

    private void jRButtonBuffetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRButtonBuffetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRButtonBuffetActionPerformed

    private void jRButtonNAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRButtonNAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRButtonNAActionPerformed

    private void jComboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoActionPerformed

        tipoEvento = jComboBoxTipo.getSelectedItem().toString();
        eEvento = eEvento.valueOf(tipoEvento);
        System.out.println("" + eEvento);
        switch (eEvento) {
            case CONGRESO:
                flagTipoEv(true);
                break;
            case BANQUETE:
                flagTipoEv(false);
                break;
            case JORNADA:
                flagTipoEv(false);
                break;
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_jComboBoxTipoActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FReserva dialog = new FReserva(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JCheckBox jCheckBoxHabitaciones;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefono;
    private javax.swing.JLabel jLabelCocina;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelJornadas;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPlazas;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRButtonBuffet;
    private javax.swing.JRadioButton jRButtonCarta;
    private javax.swing.JRadioButton jRButtonChef;
    private javax.swing.JRadioButton jRButtonNA;
    private javax.swing.JSpinner jSpinnerJornadas;
    private javax.swing.JSpinner jSpinnerPlazas;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JButton okButton;
    private javax.swing.JSpinner spinFecha;
    // End of variables declaration//GEN-END:variables

    private void doClose(int RET_OK) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
